# -*- coding: utf-8 -*-
"""AI301.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XOU-7Jb3zfi6QNzV-PMFnQvUjRNMJJt9

# Regression Model
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/Data.csv",index_col=0)
df

df.head()

df.describe()

df.shape

"""## PLOTTING A GRAPH BETWEEN EXPERIENCE AND SALARY TO CHECK IF OUR DATA IS LINEAR"""

plt.scatter(df['OnTarget'],df['Goals'],color='purple')
plt.xlabel('On Target')
plt.ylabel('Goals')

x = df.iloc[:,10:11]
y = df.iloc[:,6]
x.head()

y.head()

"""# TRAINING OUR LINEAR REGRESSION MODEL"""

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=3)
lr = LinearRegression()
lr.fit(x_train,y_train)

lr.predict(x_test.iloc[0].values.reshape(1,1))

"""# PLOTTING THE GRAPH OF OUR TRAINED REGRESSION MODEL"""

plt.scatter(df['OnTarget'],df['Goals'],color='gold')
plt.plot(x_train,lr.predict(x_train))
plt.xlabel('Goals')
plt.ylabel(' On target')

# y = mx + b [equation of a line]
m = lr.coef_ # 9418.56697369
b = lr.intercept_ # 25256.91033001527
# y = 9418.56697369 * x + 25256.91033001527

r2_score = lr.score(x_test,y_test)
print(r2_score*100)